package com.edwin.Hibernate;
// Generated Jun 2, 2013 10:21:22 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * InvmbdId generated by hbm2java
 */
public class InvmbdId  implements java.io.Serializable {


     private String mb001;
     private BigDecimal materialPrice;
     private BigDecimal laborePrice;
     private BigDecimal madePrice;
     private BigDecimal cooperationPrice;
     private BigDecimal sumPrice;
     private BigDecimal md006;
     private BigDecimal md007;
     private BigDecimal vz;

    public InvmbdId() {
    }

    public InvmbdId(String mb001, BigDecimal materialPrice, BigDecimal laborePrice, BigDecimal madePrice, BigDecimal cooperationPrice, BigDecimal sumPrice, BigDecimal md006, BigDecimal md007, BigDecimal vz) {
       this.mb001 = mb001;
       this.materialPrice = materialPrice;
       this.laborePrice = laborePrice;
       this.madePrice = madePrice;
       this.cooperationPrice = cooperationPrice;
       this.sumPrice = sumPrice;
       this.md006 = md006;
       this.md007 = md007;
       this.vz = vz;
    }
   
    public String getMb001() {
        return this.mb001;
    }
    
    public void setMb001(String mb001) {
        this.mb001 = mb001;
    }
    public BigDecimal getMaterialPrice() {
        return this.materialPrice;
    }
    
    public void setMaterialPrice(BigDecimal materialPrice) {
        this.materialPrice = materialPrice;
    }
    public BigDecimal getLaborePrice() {
        return this.laborePrice;
    }
    
    public void setLaborePrice(BigDecimal laborePrice) {
        this.laborePrice = laborePrice;
    }
    public BigDecimal getMadePrice() {
        return this.madePrice;
    }
    
    public void setMadePrice(BigDecimal madePrice) {
        this.madePrice = madePrice;
    }
    public BigDecimal getCooperationPrice() {
        return this.cooperationPrice;
    }
    
    public void setCooperationPrice(BigDecimal cooperationPrice) {
        this.cooperationPrice = cooperationPrice;
    }
    public BigDecimal getSumPrice() {
        return this.sumPrice;
    }
    
    public void setSumPrice(BigDecimal sumPrice) {
        this.sumPrice = sumPrice;
    }
    public BigDecimal getMd006() {
        return this.md006;
    }
    
    public void setMd006(BigDecimal md006) {
        this.md006 = md006;
    }
    public BigDecimal getMd007() {
        return this.md007;
    }
    
    public void setMd007(BigDecimal md007) {
        this.md007 = md007;
    }
    public BigDecimal getVz() {
        return this.vz;
    }
    
    public void setVz(BigDecimal vz) {
        this.vz = vz;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvmbdId) ) return false;
		 InvmbdId castOther = ( InvmbdId ) other; 
         
		 return ( (this.getMb001()==castOther.getMb001()) || ( this.getMb001()!=null && castOther.getMb001()!=null && this.getMb001().equals(castOther.getMb001()) ) )
 && ( (this.getMaterialPrice()==castOther.getMaterialPrice()) || ( this.getMaterialPrice()!=null && castOther.getMaterialPrice()!=null && this.getMaterialPrice().equals(castOther.getMaterialPrice()) ) )
 && ( (this.getLaborePrice()==castOther.getLaborePrice()) || ( this.getLaborePrice()!=null && castOther.getLaborePrice()!=null && this.getLaborePrice().equals(castOther.getLaborePrice()) ) )
 && ( (this.getMadePrice()==castOther.getMadePrice()) || ( this.getMadePrice()!=null && castOther.getMadePrice()!=null && this.getMadePrice().equals(castOther.getMadePrice()) ) )
 && ( (this.getCooperationPrice()==castOther.getCooperationPrice()) || ( this.getCooperationPrice()!=null && castOther.getCooperationPrice()!=null && this.getCooperationPrice().equals(castOther.getCooperationPrice()) ) )
 && ( (this.getSumPrice()==castOther.getSumPrice()) || ( this.getSumPrice()!=null && castOther.getSumPrice()!=null && this.getSumPrice().equals(castOther.getSumPrice()) ) )
 && ( (this.getMd006()==castOther.getMd006()) || ( this.getMd006()!=null && castOther.getMd006()!=null && this.getMd006().equals(castOther.getMd006()) ) )
 && ( (this.getMd007()==castOther.getMd007()) || ( this.getMd007()!=null && castOther.getMd007()!=null && this.getMd007().equals(castOther.getMd007()) ) )
 && ( (this.getVz()==castOther.getVz()) || ( this.getVz()!=null && castOther.getVz()!=null && this.getVz().equals(castOther.getVz()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMb001() == null ? 0 : this.getMb001().hashCode() );
         result = 37 * result + ( getMaterialPrice() == null ? 0 : this.getMaterialPrice().hashCode() );
         result = 37 * result + ( getLaborePrice() == null ? 0 : this.getLaborePrice().hashCode() );
         result = 37 * result + ( getMadePrice() == null ? 0 : this.getMadePrice().hashCode() );
         result = 37 * result + ( getCooperationPrice() == null ? 0 : this.getCooperationPrice().hashCode() );
         result = 37 * result + ( getSumPrice() == null ? 0 : this.getSumPrice().hashCode() );
         result = 37 * result + ( getMd006() == null ? 0 : this.getMd006().hashCode() );
         result = 37 * result + ( getMd007() == null ? 0 : this.getMd007().hashCode() );
         result = 37 * result + ( getVz() == null ? 0 : this.getVz().hashCode() );
         return result;
   }   


}


