package com.edwin.Hibernate;
// Generated Jun 2, 2013 10:21:22 PM by Hibernate Tools 3.6.0



/**
 * Invmbc generated by hbm2java
 */
public class Invmbc  implements java.io.Serializable {


     private InvmbcId id;

    public Invmbc() {
    }

    public Invmbc(InvmbcId id) {
       this.id = id;
    }
   
    public InvmbcId getId() {
        return this.id;
    }
    
    public void setId(InvmbcId id) {
        this.id = id;
    }




}


