package com.edwin.Hibernate;
// Generated Jun 2, 2013 10:21:22 PM by Hibernate Tools 3.6.0



/**
 * Invmbd generated by hbm2java
 */
public class Invmbd  implements java.io.Serializable {


     private InvmbdId id;

    public Invmbd() {
    }

    public Invmbd(InvmbdId id) {
       this.id = id;
    }
   
    public InvmbdId getId() {
        return this.id;
    }
    
    public void setId(InvmbdId id) {
        this.id = id;
    }




}


