package com.edwin.Hibernate;
// Generated Jun 2, 2013 10:21:22 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Purma generated by hbm2java
 */
public class Purma  implements java.io.Serializable {


     private String ma001;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String ma002;
     private String ma003;
     private String ma004;
     private String ma005;
     private String ma006;
     private String ma007;
     private String ma008;
     private String ma009;
     private String ma010;
     private String ma011;
     private String ma012;
     private String ma013;
     private String ma014;
     private String ma015;
     private Character ma016;
     private String ma017;
     private BigDecimal ma018;
     private Integer ma019;
     private Character ma020;
     private String ma021;
     private String ma022;
     private String ma023;
     private String ma024;
     private String ma025;
     private String ma026;
     private String ma027;
     private String ma028;
     private Character ma029;
     private Character ma030;
     private Character ma031;
     private Character ma032;
     private Character ma033;
     private Character ma034;
     private String ma035;
     private Character ma036;
     private String ma037;
     private Character ma038;
     private String ma039;
     private String ma040;
     private String ma041;
     private String ma042;
     private String ma043;
     private Character ma044;
     private Character ma045;
     private String ma046;
     private String ma047;
     private String ma048;
     private String ma049;
     private String ma050;
     private String ma051;
     private String ma052;
     private Character ma053;
     private BigDecimal ma054;
     private String ma055;
     private Character ma056;
     private Character ma057;
     private BigDecimal ma058;
     private String ma059;
     private Character ma060;
     private String ma061;
     private String ma062;
     private String ma063;
     private BigDecimal ma064;
     private String ma065;
     private Short ma066;
     private String ma067;
     private String ma068;
     private Character ma069;
     private String ma070;
     private String ma071;
     private BigDecimal ma072;
     private BigDecimal ma073;
     private BigDecimal ma074;
     private String ma075;
     private Character ma076;
     private Character ma077;
     private String ma078;
     private String ma079;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Purma() {
    }

	
    public Purma(String ma001) {
        this.ma001 = ma001;
    }
    public Purma(String ma001, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String ma002, String ma003, String ma004, String ma005, String ma006, String ma007, String ma008, String ma009, String ma010, String ma011, String ma012, String ma013, String ma014, String ma015, Character ma016, String ma017, BigDecimal ma018, Integer ma019, Character ma020, String ma021, String ma022, String ma023, String ma024, String ma025, String ma026, String ma027, String ma028, Character ma029, Character ma030, Character ma031, Character ma032, Character ma033, Character ma034, String ma035, Character ma036, String ma037, Character ma038, String ma039, String ma040, String ma041, String ma042, String ma043, Character ma044, Character ma045, String ma046, String ma047, String ma048, String ma049, String ma050, String ma051, String ma052, Character ma053, BigDecimal ma054, String ma055, Character ma056, Character ma057, BigDecimal ma058, String ma059, Character ma060, String ma061, String ma062, String ma063, BigDecimal ma064, String ma065, Short ma066, String ma067, String ma068, Character ma069, String ma070, String ma071, BigDecimal ma072, BigDecimal ma073, BigDecimal ma074, String ma075, Character ma076, Character ma077, String ma078, String ma079, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.ma001 = ma001;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.ma002 = ma002;
       this.ma003 = ma003;
       this.ma004 = ma004;
       this.ma005 = ma005;
       this.ma006 = ma006;
       this.ma007 = ma007;
       this.ma008 = ma008;
       this.ma009 = ma009;
       this.ma010 = ma010;
       this.ma011 = ma011;
       this.ma012 = ma012;
       this.ma013 = ma013;
       this.ma014 = ma014;
       this.ma015 = ma015;
       this.ma016 = ma016;
       this.ma017 = ma017;
       this.ma018 = ma018;
       this.ma019 = ma019;
       this.ma020 = ma020;
       this.ma021 = ma021;
       this.ma022 = ma022;
       this.ma023 = ma023;
       this.ma024 = ma024;
       this.ma025 = ma025;
       this.ma026 = ma026;
       this.ma027 = ma027;
       this.ma028 = ma028;
       this.ma029 = ma029;
       this.ma030 = ma030;
       this.ma031 = ma031;
       this.ma032 = ma032;
       this.ma033 = ma033;
       this.ma034 = ma034;
       this.ma035 = ma035;
       this.ma036 = ma036;
       this.ma037 = ma037;
       this.ma038 = ma038;
       this.ma039 = ma039;
       this.ma040 = ma040;
       this.ma041 = ma041;
       this.ma042 = ma042;
       this.ma043 = ma043;
       this.ma044 = ma044;
       this.ma045 = ma045;
       this.ma046 = ma046;
       this.ma047 = ma047;
       this.ma048 = ma048;
       this.ma049 = ma049;
       this.ma050 = ma050;
       this.ma051 = ma051;
       this.ma052 = ma052;
       this.ma053 = ma053;
       this.ma054 = ma054;
       this.ma055 = ma055;
       this.ma056 = ma056;
       this.ma057 = ma057;
       this.ma058 = ma058;
       this.ma059 = ma059;
       this.ma060 = ma060;
       this.ma061 = ma061;
       this.ma062 = ma062;
       this.ma063 = ma063;
       this.ma064 = ma064;
       this.ma065 = ma065;
       this.ma066 = ma066;
       this.ma067 = ma067;
       this.ma068 = ma068;
       this.ma069 = ma069;
       this.ma070 = ma070;
       this.ma071 = ma071;
       this.ma072 = ma072;
       this.ma073 = ma073;
       this.ma074 = ma074;
       this.ma075 = ma075;
       this.ma076 = ma076;
       this.ma077 = ma077;
       this.ma078 = ma078;
       this.ma079 = ma079;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public String getMa001() {
        return this.ma001;
    }
    
    public void setMa001(String ma001) {
        this.ma001 = ma001;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getMa002() {
        return this.ma002;
    }
    
    public void setMa002(String ma002) {
        this.ma002 = ma002;
    }
    public String getMa003() {
        return this.ma003;
    }
    
    public void setMa003(String ma003) {
        this.ma003 = ma003;
    }
    public String getMa004() {
        return this.ma004;
    }
    
    public void setMa004(String ma004) {
        this.ma004 = ma004;
    }
    public String getMa005() {
        return this.ma005;
    }
    
    public void setMa005(String ma005) {
        this.ma005 = ma005;
    }
    public String getMa006() {
        return this.ma006;
    }
    
    public void setMa006(String ma006) {
        this.ma006 = ma006;
    }
    public String getMa007() {
        return this.ma007;
    }
    
    public void setMa007(String ma007) {
        this.ma007 = ma007;
    }
    public String getMa008() {
        return this.ma008;
    }
    
    public void setMa008(String ma008) {
        this.ma008 = ma008;
    }
    public String getMa009() {
        return this.ma009;
    }
    
    public void setMa009(String ma009) {
        this.ma009 = ma009;
    }
    public String getMa010() {
        return this.ma010;
    }
    
    public void setMa010(String ma010) {
        this.ma010 = ma010;
    }
    public String getMa011() {
        return this.ma011;
    }
    
    public void setMa011(String ma011) {
        this.ma011 = ma011;
    }
    public String getMa012() {
        return this.ma012;
    }
    
    public void setMa012(String ma012) {
        this.ma012 = ma012;
    }
    public String getMa013() {
        return this.ma013;
    }
    
    public void setMa013(String ma013) {
        this.ma013 = ma013;
    }
    public String getMa014() {
        return this.ma014;
    }
    
    public void setMa014(String ma014) {
        this.ma014 = ma014;
    }
    public String getMa015() {
        return this.ma015;
    }
    
    public void setMa015(String ma015) {
        this.ma015 = ma015;
    }
    public Character getMa016() {
        return this.ma016;
    }
    
    public void setMa016(Character ma016) {
        this.ma016 = ma016;
    }
    public String getMa017() {
        return this.ma017;
    }
    
    public void setMa017(String ma017) {
        this.ma017 = ma017;
    }
    public BigDecimal getMa018() {
        return this.ma018;
    }
    
    public void setMa018(BigDecimal ma018) {
        this.ma018 = ma018;
    }
    public Integer getMa019() {
        return this.ma019;
    }
    
    public void setMa019(Integer ma019) {
        this.ma019 = ma019;
    }
    public Character getMa020() {
        return this.ma020;
    }
    
    public void setMa020(Character ma020) {
        this.ma020 = ma020;
    }
    public String getMa021() {
        return this.ma021;
    }
    
    public void setMa021(String ma021) {
        this.ma021 = ma021;
    }
    public String getMa022() {
        return this.ma022;
    }
    
    public void setMa022(String ma022) {
        this.ma022 = ma022;
    }
    public String getMa023() {
        return this.ma023;
    }
    
    public void setMa023(String ma023) {
        this.ma023 = ma023;
    }
    public String getMa024() {
        return this.ma024;
    }
    
    public void setMa024(String ma024) {
        this.ma024 = ma024;
    }
    public String getMa025() {
        return this.ma025;
    }
    
    public void setMa025(String ma025) {
        this.ma025 = ma025;
    }
    public String getMa026() {
        return this.ma026;
    }
    
    public void setMa026(String ma026) {
        this.ma026 = ma026;
    }
    public String getMa027() {
        return this.ma027;
    }
    
    public void setMa027(String ma027) {
        this.ma027 = ma027;
    }
    public String getMa028() {
        return this.ma028;
    }
    
    public void setMa028(String ma028) {
        this.ma028 = ma028;
    }
    public Character getMa029() {
        return this.ma029;
    }
    
    public void setMa029(Character ma029) {
        this.ma029 = ma029;
    }
    public Character getMa030() {
        return this.ma030;
    }
    
    public void setMa030(Character ma030) {
        this.ma030 = ma030;
    }
    public Character getMa031() {
        return this.ma031;
    }
    
    public void setMa031(Character ma031) {
        this.ma031 = ma031;
    }
    public Character getMa032() {
        return this.ma032;
    }
    
    public void setMa032(Character ma032) {
        this.ma032 = ma032;
    }
    public Character getMa033() {
        return this.ma033;
    }
    
    public void setMa033(Character ma033) {
        this.ma033 = ma033;
    }
    public Character getMa034() {
        return this.ma034;
    }
    
    public void setMa034(Character ma034) {
        this.ma034 = ma034;
    }
    public String getMa035() {
        return this.ma035;
    }
    
    public void setMa035(String ma035) {
        this.ma035 = ma035;
    }
    public Character getMa036() {
        return this.ma036;
    }
    
    public void setMa036(Character ma036) {
        this.ma036 = ma036;
    }
    public String getMa037() {
        return this.ma037;
    }
    
    public void setMa037(String ma037) {
        this.ma037 = ma037;
    }
    public Character getMa038() {
        return this.ma038;
    }
    
    public void setMa038(Character ma038) {
        this.ma038 = ma038;
    }
    public String getMa039() {
        return this.ma039;
    }
    
    public void setMa039(String ma039) {
        this.ma039 = ma039;
    }
    public String getMa040() {
        return this.ma040;
    }
    
    public void setMa040(String ma040) {
        this.ma040 = ma040;
    }
    public String getMa041() {
        return this.ma041;
    }
    
    public void setMa041(String ma041) {
        this.ma041 = ma041;
    }
    public String getMa042() {
        return this.ma042;
    }
    
    public void setMa042(String ma042) {
        this.ma042 = ma042;
    }
    public String getMa043() {
        return this.ma043;
    }
    
    public void setMa043(String ma043) {
        this.ma043 = ma043;
    }
    public Character getMa044() {
        return this.ma044;
    }
    
    public void setMa044(Character ma044) {
        this.ma044 = ma044;
    }
    public Character getMa045() {
        return this.ma045;
    }
    
    public void setMa045(Character ma045) {
        this.ma045 = ma045;
    }
    public String getMa046() {
        return this.ma046;
    }
    
    public void setMa046(String ma046) {
        this.ma046 = ma046;
    }
    public String getMa047() {
        return this.ma047;
    }
    
    public void setMa047(String ma047) {
        this.ma047 = ma047;
    }
    public String getMa048() {
        return this.ma048;
    }
    
    public void setMa048(String ma048) {
        this.ma048 = ma048;
    }
    public String getMa049() {
        return this.ma049;
    }
    
    public void setMa049(String ma049) {
        this.ma049 = ma049;
    }
    public String getMa050() {
        return this.ma050;
    }
    
    public void setMa050(String ma050) {
        this.ma050 = ma050;
    }
    public String getMa051() {
        return this.ma051;
    }
    
    public void setMa051(String ma051) {
        this.ma051 = ma051;
    }
    public String getMa052() {
        return this.ma052;
    }
    
    public void setMa052(String ma052) {
        this.ma052 = ma052;
    }
    public Character getMa053() {
        return this.ma053;
    }
    
    public void setMa053(Character ma053) {
        this.ma053 = ma053;
    }
    public BigDecimal getMa054() {
        return this.ma054;
    }
    
    public void setMa054(BigDecimal ma054) {
        this.ma054 = ma054;
    }
    public String getMa055() {
        return this.ma055;
    }
    
    public void setMa055(String ma055) {
        this.ma055 = ma055;
    }
    public Character getMa056() {
        return this.ma056;
    }
    
    public void setMa056(Character ma056) {
        this.ma056 = ma056;
    }
    public Character getMa057() {
        return this.ma057;
    }
    
    public void setMa057(Character ma057) {
        this.ma057 = ma057;
    }
    public BigDecimal getMa058() {
        return this.ma058;
    }
    
    public void setMa058(BigDecimal ma058) {
        this.ma058 = ma058;
    }
    public String getMa059() {
        return this.ma059;
    }
    
    public void setMa059(String ma059) {
        this.ma059 = ma059;
    }
    public Character getMa060() {
        return this.ma060;
    }
    
    public void setMa060(Character ma060) {
        this.ma060 = ma060;
    }
    public String getMa061() {
        return this.ma061;
    }
    
    public void setMa061(String ma061) {
        this.ma061 = ma061;
    }
    public String getMa062() {
        return this.ma062;
    }
    
    public void setMa062(String ma062) {
        this.ma062 = ma062;
    }
    public String getMa063() {
        return this.ma063;
    }
    
    public void setMa063(String ma063) {
        this.ma063 = ma063;
    }
    public BigDecimal getMa064() {
        return this.ma064;
    }
    
    public void setMa064(BigDecimal ma064) {
        this.ma064 = ma064;
    }
    public String getMa065() {
        return this.ma065;
    }
    
    public void setMa065(String ma065) {
        this.ma065 = ma065;
    }
    public Short getMa066() {
        return this.ma066;
    }
    
    public void setMa066(Short ma066) {
        this.ma066 = ma066;
    }
    public String getMa067() {
        return this.ma067;
    }
    
    public void setMa067(String ma067) {
        this.ma067 = ma067;
    }
    public String getMa068() {
        return this.ma068;
    }
    
    public void setMa068(String ma068) {
        this.ma068 = ma068;
    }
    public Character getMa069() {
        return this.ma069;
    }
    
    public void setMa069(Character ma069) {
        this.ma069 = ma069;
    }
    public String getMa070() {
        return this.ma070;
    }
    
    public void setMa070(String ma070) {
        this.ma070 = ma070;
    }
    public String getMa071() {
        return this.ma071;
    }
    
    public void setMa071(String ma071) {
        this.ma071 = ma071;
    }
    public BigDecimal getMa072() {
        return this.ma072;
    }
    
    public void setMa072(BigDecimal ma072) {
        this.ma072 = ma072;
    }
    public BigDecimal getMa073() {
        return this.ma073;
    }
    
    public void setMa073(BigDecimal ma073) {
        this.ma073 = ma073;
    }
    public BigDecimal getMa074() {
        return this.ma074;
    }
    
    public void setMa074(BigDecimal ma074) {
        this.ma074 = ma074;
    }
    public String getMa075() {
        return this.ma075;
    }
    
    public void setMa075(String ma075) {
        this.ma075 = ma075;
    }
    public Character getMa076() {
        return this.ma076;
    }
    
    public void setMa076(Character ma076) {
        this.ma076 = ma076;
    }
    public Character getMa077() {
        return this.ma077;
    }
    
    public void setMa077(Character ma077) {
        this.ma077 = ma077;
    }
    public String getMa078() {
        return this.ma078;
    }
    
    public void setMa078(String ma078) {
        this.ma078 = ma078;
    }
    public String getMa079() {
        return this.ma079;
    }
    
    public void setMa079(String ma079) {
        this.ma079 = ma079;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


